### Loading and preprocessing the data

http://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html#sklearn.datasets.load_iris

Classes	3
Samples per class	50
Samples total	150
Dimensionality	4

In [1]:
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()

In [3]:
type(iris)

sklearn.datasets.base.Bunch

In [4]:
iris.data.shape

(150L, 4L)

In [5]:
iris.data

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [6]:
list(iris.target_names)

['setosa', 'versicolor', 'virginica']

In [7]:
list(iris.feature_names)

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], 
      dtype='|S10')

In [10]:
iris.DESCR

'Iris Plants Database\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n    :Missi

### Let's set our training data = X

In [11]:
X = iris.data
X.shape

(150L, 4L)

### The classes are already converted to integer labels where 0=Iris-Setosa, 1=Iris-Versicolor, 2=Iris-Virginica. Let's set y = iris.target.

In [12]:
y = iris.target

print('Class labels:', np.unique(y))

('Class labels:', array([0, 1, 2]))


### For this demo, let's just look at predicting iris-versicolor (y=1). So we set the values for y where y = 0 or 2 to 0.

In [13]:
y[y==2] = 0
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Let's try a logistic regression.

### First, we will split the data into 80% train, 20% test.

In [14]:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Next, we standardize.

In [15]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

### Then, we import the classes necessary to run logistic regression and we train on the training data and test on the test set.
http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [16]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train_std,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [85]:
print(clf.coef_)
print(clf.intercept_)

[[-0.11204582 -1.14230167  0.81255397 -0.75535923]]
[-0.99525833]


In [87]:
y_pred = clf.predict(X_test_std)
y_pred.shape

(30,)

In [88]:
# you can import sklearn's accuracy function and compute accuracy from that
#http://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.66666666666666663

In [89]:
# or write the function yourself
(sum(y_test==y_pred))/len(y_test)

0.66666666666666663

In [105]:
#if you want to output the probabilities:
y_pred_proba = clf.predict_proba(X_test_std)

In [106]:
y_pred_proba

array([[ 0.70407063,  0.29592937],
       [ 0.17293063,  0.82706937],
       [ 0.98349949,  0.01650051],
       [ 0.54887661,  0.45112339],
       [ 0.864263  ,  0.135737  ],
       [ 0.87513   ,  0.12487   ],
       [ 0.90936095,  0.09063905],
       [ 0.74768674,  0.25231326],
       [ 0.53976164,  0.46023836],
       [ 0.58292807,  0.41707193],
       [ 0.30361946,  0.69638054],
       [ 0.80276063,  0.19723937],
       [ 0.47929211,  0.52070789],
       [ 0.57659316,  0.42340684],
       [ 0.59340827,  0.40659173],
       [ 0.71980251,  0.28019749],
       [ 0.63505247,  0.36494753],
       [ 0.36440568,  0.63559432],
       [ 0.71212828,  0.28787172],
       [ 0.97121829,  0.02878171],
       [ 0.63204446,  0.36795554],
       [ 0.68278937,  0.31721063],
       [ 0.83778501,  0.16221499],
       [ 0.62000086,  0.37999914],
       [ 0.61555648,  0.38444352],
       [ 0.92810811,  0.07189189],
       [ 0.94975272,  0.05024728],
       [ 0.61691621,  0.38308379],
       [ 0.24755191,

In [107]:
y_pred_proba.shape

(30, 2)

In [108]:
y_pred_proba = clf.predict_proba(X_test_std)[:,1]

In [111]:
y_pred_proba

array([ 0.29592937,  0.82706937,  0.01650051,  0.45112339,  0.135737  ,
        0.12487   ,  0.09063905,  0.25231326,  0.46023836,  0.41707193,
        0.69638054,  0.19723937,  0.52070789,  0.42340684,  0.40659173,
        0.28019749,  0.36494753,  0.63559432,  0.28787172,  0.02878171,
        0.36795554,  0.31721063,  0.16221499,  0.37999914,  0.38444352,
        0.07189189,  0.05024728,  0.38308379,  0.75244809,  0.11911815])

In [112]:
#compute auc
from sklearn.metrics import roc_auc_score
print(roc_auc_score(y_test,y_pred_proba))

0.828054298643


In [118]:
from sklearn.metrics import roc_curve
fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba, pos_label=1)
print(fpr)
print(tpr)
print(thresholds)

[ 0.          0.          0.05882353  0.05882353  0.11764706  0.11764706
  0.17647059  0.17647059  0.29411765  0.29411765  0.47058824  0.47058824
  1.        ]
[ 0.07692308  0.15384615  0.15384615  0.38461538  0.38461538  0.61538462
  0.61538462  0.69230769  0.69230769  0.84615385  0.84615385  1.          1.        ]
[ 0.82706937  0.75244809  0.69638054  0.46023836  0.45112339  0.40659173
  0.38444352  0.38308379  0.36795554  0.31721063  0.28019749  0.19723937
  0.01650051]


In [122]:
print(fpr.shape)

(13,)

In [128]:
np.column_stack((thresholds,tpr,fpr))

array([[ 0.82706937,  0.07692308,  0.        ],
       [ 0.75244809,  0.15384615,  0.        ],
       [ 0.69638054,  0.15384615,  0.05882353],
       [ 0.46023836,  0.38461538,  0.05882353],
       [ 0.45112339,  0.38461538,  0.11764706],
       [ 0.40659173,  0.61538462,  0.11764706],
       [ 0.38444352,  0.61538462,  0.17647059],
       [ 0.38308379,  0.69230769,  0.17647059],
       [ 0.36795554,  0.69230769,  0.29411765],
       [ 0.31721063,  0.84615385,  0.29411765],
       [ 0.28019749,  0.84615385,  0.47058824],
       [ 0.19723937,  1.        ,  0.47058824],
       [ 0.01650051,  1.        ,  1.        ]])

In [131]:
#cross validation with pipeline
from sklearn.pipeline import Pipeline
pipe_lr=Pipeline([
        ('scl',StandardScaler()),
        ('clf',LogisticRegression())
    ])
#stratified k-fold cv
#For integer inputs for cv, if y is binary or multiclass, StratifiedKFold is used by default by cross_val_score
from sklearn.cross_validation import cross_val_score
scores=cross_val_score(estimator=pipe_lr,X=X_train_std,y=y_train,cv=5,n_jobs=1,scoring='roc_auc')
print ('CV accuracy: %.3f +/- %.3f' % (np.mean(scores),np.std(scores)))
print (scores)

CV accuracy: 0.782 +/- 0.078
[ 0.70588235  0.67647059  0.82352941  0.88392857  0.82142857]


In [133]:
#grid search
from sklearn.grid_search import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from time import time
pipe_lr=Pipeline([
        ('scl',StandardScaler()),
        ('clf',LogisticRegression())
    ])
param_range=[0.01,0.1,1.0]
param_grid={'clf__C': param_range}

start=time()
gs=GridSearchCV(estimator=pipe_lr,param_grid=param_grid,scoring='roc_auc',cv=5,n_jobs=-1)
gs = gs.fit(X_train_std,y_train)
print (time() - start)

print(gs.best_score_)
print(gs.best_params_)
print(gs.grid_scores_)

2.0432043075561523
0.782860644258
{'clf__C': 0.1}
[mean: 0.76129, std: 0.09929, params: {'clf__C': 0.01}, mean: 0.78286, std: 0.08310, params: {'clf__C': 0.1}, mean: 0.77956, std: 0.07823, params: {'clf__C': 1.0}]
